services:
  buchori-family:
    build: .
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-global.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - buchori-family
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
